export interface MetricRow {
  index: number; // 0-based index
  label: string;
  type: 'header' | 'data' | 'formula' | 'section';
  value: number;
  isCustomOverride?: boolean; // If overridden by user
  formula?: string; // Informational formula description
}

export const FINANCIAL_TEMPLATE: Omit<MetricRow, 'value'>[] = [
  { index: 0, label: "Выручка общая", type: "formula", formula: "Сумма статей выручки (без Инвесторов)" },
  { index: 1, label: "Выручка с услуг", type: "data" },
  { index: 2, label: "Выручка с товаров", type: "data" },
  { index: 3, label: "Пополнение счёта", type: "data" },
  { index: 4, label: "Выручка с сертификатов", type: "data" },
  { index: 5, label: "Доход от продажи абонементов", type: "data" },
  { index: 6, label: "Прочие доходы", type: "data" },
  { index: 7, label: "ИНВЕСТОРЫ", type: "data" },
  { index: 8, label: "Расходы", type: "formula", formula: "Переменные + Постоянные + Поставщики + ЗП + Прочие + Налоги" },
  { index: 9, label: "Расходы переменные", type: "formula", formula: "Сумма переменных расходов" },
  { index: 10, label: "Для мастеров", type: "data" },
  { index: 11, label: "2026 Жизнеобеспечение салона", type: "formula", formula: "Сумма расходов на жизнеобеспечение" },
  { index: 12, label: "Доставка", type: "data" },
  { index: 13, label: "Канцелярия", type: "data" },
  { index: 14, label: "Расходники для уборки и подсобки", type: "data" },
  { index: 15, label: "Такси", type: "data" },
  { index: 16, label: "Аптечка, лекарства", type: "data" },
  { index: 17, label: "Печатная продукция (Сертификаты, пакеты, наклейки, типография)", type: "data" },
  { index: 18, label: "Санитарные требования (антисептики, бахилы и т. п.)", type: "data" },
  { index: 19, label: "ремонт, устранение неполадок (зп разнорабочим и материалы)", type: "data" },
  { index: 20, label: "электроприборы, мебель, оборудование и д. р. хозтовары", type: "data" },
  { index: 21, label: "Конфеты для сотрудников", type: "data" },
  { index: 22, label: "Академия", type: "data" },
  { index: 23, label: "Сервис для гостей", type: "formula", formula: "Сумма по сервису для гостей" },
  { index: 24, label: "Вода волжанка", type: "data" },
  { index: 25, label: "Алкогольные напитки", type: "data" },
  { index: 26, label: "Конфеты, шоколад", type: "data" },
  { index: 27, label: "Кофе", type: "data" },
  { index: 28, label: "Молоко (обычное/альтернативное)", type: "data" },
  { index: 29, label: "Одноразовая продукция (стаканчики пластик/бумаж, трубочки, салфетки)", type: "data" },
  { index: 30, label: "Сахар / Сиропы", type: "data" },
  { index: 31, label: "Сезонные покупки", type: "data" },
  { index: 32, label: "Туалетная комната", type: "data" },
  { index: 33, label: "Чай", type: "data" },
  { index: 34, label: "Другие расходы", type: "data" },
  { index: 35, label: "Переменные// Возвраты", type: "data" },
  { index: 36, label: "Расходы постоянные", type: "formula", formula: "Сумма постоянных расходов" },
  { index: 37, label: "Подписки на что‑либо", type: "data" },
  { index: 38, label: "Аренда", type: "data" },
  { index: 39, label: "Бухгалтер", type: "data" },
  { index: 40, label: "Коммунальные платежи", type: "data" },
  { index: 41, label: "Охрана", type: "data" },
  { index: 42, label: "Связь (интернет, моб. телефон)", type: "data" },
  { index: 43, label: "Комиссия по карте", type: "data" },
  { index: 44, label: "Комиссия по эквайрингу", type: "data" },
  { index: 45, label: "Кредит", type: "data" },
  { index: 46, label: "Комиссия по эквайрингу (юкасса, автоматическая)", type: "data" },
  { index: 47, label: "Перемещения LIQ|FLS (расходы на такси мастеров, перемещение косметики, видеосвета и т. п.)", type: "data" },
  { index: 48, label: "Привлечения новых сотрудников (оплата объявлений и др. расходы)", type: "data" },
  { index: 49, label: "Реклама, маркетинг, таргет", type: "data" },
  { index: 50, label: "СРМ система. Программное обеспечение. ПО (онлайн запись и т. д.)", type: "data" },
  { index: 51, label: "Корпоративная деятельность", type: "data" },
  { index: 52, label: "Процент свадебным распорядителям", type: "data" },
  { index: 53, label: "Поставщики", type: "formula", formula: "Сумма по поставщикам" },
  { index: 54, label: "ИП Щеголькова (Ипатова/Власов) (ProfiLine)", type: "data" },
  { index: 55, label: "ИП Щеголькова (Ипатова/Власов) (American CREW)", type: "data" },
  { index: 56, label: "ИП Щеголькова (Ипатова/Власов) (Constant Delight расходники)", type: "data" },
  { index: 57, label: "ИП Щеголькова (Ипатова/Власов) (Constant Delight витрина)", type: "data" },
  { index: 58, label: "ИП Худорожков/Демин (расходники)", type: "data" },
  { index: 59, label: "OOO «Торговый Дом „БлескСервис“» (TORK) (Расходники)", type: "data" },
  { index: 60, label: "Материалы для бровистов", type: "data" },
  { index: 61, label: "Материалы для ногтевиков", type: "data" },
  { index: 62, label: "Материалы для ресниц", type: "data" },
  { index: 63, label: "Материалы для эпиляции", type: "data" },
  { index: 64, label: "Расходники для барберов", type: "data" },
  { index: 65, label: "Косметика на продажу", type: "data" },
  { index: 66, label: "ИП Калашникова (Matrix расходники)", type: "data" },
  { index: 67, label: "ИП Калашникова (L`Oreal расходники)", type: "data" },
  { index: 68, label: "ИП Калашникова (Matrix витрина)", type: "data" },
  { index: 69, label: "ИП Калашникова(L’Oreal витрина)", type: "data" },
  { index: 70, label: "ИП Коротков (Дайвинес)", type: "data" },
  { index: 71, label: "Керастас", type: "data" },
  { index: 72, label: "ООО «ГЕРА ГРУП»", type: "data" },
  { index: 73, label: "Эстель, Кутюр", type: "data" },
  { index: 74, label: "DR.HURTINA", type: "data" },
  { index: 75, label: "Organic Works", type: "data" },
  { index: 76, label: "Уходы без поставщика (бикси/хим и т. д.)", type: "data" },
  { index: 77, label: "Товары на продажу (Украшения на витрину)", type: "data" },
  { index: 78, label: "ИП Щеголькова (KEUNE)", type: "data" },
  { index: 79, label: "ООО «Солком Регион» (Лореаль витрина)", type: "data" },
  { index: 80, label: "ООО «Солком Регион» (Лореаль расходники)", type: "data" },
  { index: 81, label: "ООО «Солком Регион» (Матрикс расходники)", type: "data" },
  { index: 82, label: "Заказ с маркетплейсов (Ozon, WB, Яндекс Маркет)", type: "data" },
  { index: 83, label: "ООО «Эстель Сервис Поволжье»", type: "data" },
  { index: 84, label: "Чавга Полина(KEUNE)", type: "data" },
  { index: 85, label: "Прочие закупки", type: "data" },
  { index: 86, label: "L’Occitane (Локситан)", type: "data" },
  { index: 87, label: "Расходы на заработную плату", type: "formula", formula: "Зарплата мастеров + Зарплата административного персонала" },
  { index: 88, label: "Зарплата административного персонала", type: "data" },
  { index: 89, label: "Зарплата мастеров", type: "data" },
  { index: 90, label: "Зарплата выплаченная", type: "data" },
  { index: 91, label: "Прочие", type: "data" },
  { index: 92, label: "НАЛОГИ", type: "data" },
  { index: 93, label: "Прибыль теоретическая", type: "formula", formula: "Выручка общая + Расходы" },
  { index: 94, label: "Дополнительные расходы", type: "formula", formula: "Сумма доп. расходов" },
  { index: 95, label: "Предстартовые", type: "data" },
  { index: 96, label: "ЗП Разнорабочие", type: "data" },
  { index: 97, label: "Оборудование и стройматериалы для ремонта", type: "data" },
  { index: 98, label: "Оборудование, электроника и обустройство зон салона", type: "data" },
  { index: 99, label: "Оборудование и обустройство зон мастеров", type: "data" },
  { index: 100, label: "Кредиты", type: "data" },
  { index: 101, label: "Погашение долгов инвесторам", type: "data" },
  { index: 102, label: "Погашение долгов аренда", type: "data" },
  { index: 103, label: "Отчисления в фонды", type: "formula", formula: "(Прибыль теоретическая * 0.2 + 70000) * -1" },
  { index: 104, label: "Расходы за счёт фондов", type: "formula", formula: "Сумма расходов фондов" },
  { index: 105, label: "Корпоративная деятельность (списания по кассе фонда)", type: "data" },
  { index: 106, label: "Корпоративные премии (списание по кассе фонда)", type: "data" },
  { index: 107, label: "Реклама, маркетинг, таргет", type: "data" },
  { index: 108, label: "Обучения персонала (оплаты с фондов)", type: "data" },
  { index: 109, label: "Жизнеобеспечение (Оборудование, электроника и обустройство зон мастеров)", type: "data" },
  { index: 110, label: "Жизнеобеспечение (Оборудование, электроника и обустройство салона)", type: "data" },
  { index: 111, label: "Налоги", type: "data" },
  { index: 112, label: "ЧИСТАЯ ПРИБЫЛЬ", type: "formula", formula: "Прибыль теоретическая + Отчисления в фонды" },
  { index: 113, label: "Рентабельность", type: "formula", formula: "Чистая прибыль / Расходы" },
  { index: 114, label: "ПРИБЫЛЬ — доп. расходы", type: "formula", formula: "Чистая прибыль + Дополнительные расходы" },
  { index: 115, label: "Выплаты учредителям", type: "data" },
  { index: 116, label: "ФОНДЫ", type: "section" },
  { index: 117, label: "Сальдо на начало периода", type: "data" },
  { index: 118, label: "Поступления за месяц", type: "data" },
  { index: 119, label: "Уплата налогов", type: "data" },
  { index: 120, label: "Обустройство и оборудование салона", type: "data" },
  { index: 121, label: "Корпоративная деятельность", type: "data" },
  { index: 122, label: "Обучения и доп. премии", type: "data" },
  { index: 123, label: "Отпуска сотрудников", type: "data" },
  { index: 124, label: "Реклама и развитие", type: "data" },
  { index: 125, label: "Стабилизационный фонд", type: "data" },
  { index: 126, label: "Расходы за месяц", type: "formula", formula: "Сумма по фондам" },
  { index: 127, label: "Сальдо на конец периода", type: "formula", formula: "Начало + Поступления - Расходы" },
  { index: 128, label: "Прибыль", type: "data" },
  { index: 129, label: "Рентабельность", type: "data" },
  { index: 130, label: "Распределение прибыли", type: "section" },
  { index: 131, label: "Ренат", type: "data" },
  { index: 132, label: "Надежда", type: "data" },
  { index: 133, label: "L.I.Q", type: "data" },
  { index: 134, label: "сумма", type: "formula", formula: "Ренат + Надежда + LIQ" },
  { index: 135, label: "% от прибыли зп мастера", type: "data" },
  { index: 136, label: "сумма", type: "data" },
  { index: 137, label: "% от прибыли зп админы+Лариса, Вика, Алина", type: "data" },
  { index: 138, label: "сумма", type: "data" },
  { index: 139, label: "% от прибыли все", type: "data" },
  { index: 140, label: "сумма", type: "data" }
];
